export const moodBubblesFacts = [
  'Progress often happens when no one is watching. Quiet effort today can become visible results tomorrow.',
  'Trying again after a setback is a sign of strength. Every new attempt builds more experience.',
  'Small improvements add up over time. What feels tiny today can become a big change later.',
  'Confidence grows through action. The more you do, the more natural it starts to feel.',
  'Not every step needs to be perfect. Moving forward matters more than doing everything flawlessly.',
  'Sometimes the best idea appears after a pause. Giving your mind space can create new clarity.',
  'Every challenge is also a chance to learn something useful. Even difficult moments can bring valuable lessons.',
  "You don't have to rush everything. Slow and steady progress can be very powerful.",
  'New skills are built through repetition. Each attempt strengthens what you already know.',
  "Doubt can appear, but it doesn't have to decide the outcome. Your actions matter more than your worries.",
  'Every day is a chance to practice something new. Small practice sessions create lasting results.',
  'Creativity often starts with curiosity. Asking simple questions can lead to surprising discoveries.',
  'Improvement usually comes step by step. Big results rarely happen all at once.',
  'Trying something unfamiliar can open unexpected doors. New experiences expand your possibilities.',
  'A positive mindset helps you notice opportunities faster. Perspective can change how situations feel.',
  'Patience allows good things to develop naturally. Some progress simply takes time.',
  'Focus on what you can do today. Small actions now can shape a better tomorrow.',
  'Learning never really stops. Every experience adds another piece to your knowledge.',
  'Even simple efforts can create meaningful progress. Consistency turns small actions into real results.',
  'The journey forward is built from many small decisions. Each choice helps guide where you go next.',
  'Big results often begin with small, simple actions. What seems tiny today can become important tomorrow.',
  "You don't have to figure everything out at once. One step at a time is more than enough.",
  "Trying something new can feel uncomfortable, but that's usually where growth begins.",
  'Every experience teaches something, even if the lesson isn\'t obvious right away.',
  "Progress doesn't always look dramatic. Sometimes it's just being a little better than yesterday.",
  'Your effort today is building something for the future. Even small work matters.',
  "The first step is rarely perfect, but it's always important. Starting is often the hardest part.",
  'Curiosity can lead you further than certainty. Being open to learning creates new paths.',
  'Every attempt adds a little more knowledge. Experience grows quietly with each try.',
  'A fresh perspective can change how a situation feels. Sometimes a small shift in thinking helps a lot.',
  'Consistent effort builds stronger results over time. Small habits create big outcomes.',
  "It's okay to take breaks along the way. Rest helps energy return stronger.",
  'Trying again after a pause can bring better results. Time often brings clarity.',
  'New opportunities often appear when you stay open to them. Paying attention can reveal them.',
  'Confidence is built gradually. Each small success strengthens it.',
  'Even small wins deserve recognition. They are signs that progress is happening.',
  'Challenges can reveal abilities you didn\'t know you had. Difficult moments sometimes uncover strength.',
  'Moving forward is more important than moving fast. Direction matters more than speed.',
  'Each day offers a new chance to try something differently. Change can begin anytime.',
  'Progress is a journey made from many small choices. Every positive step counts.',
];
